name: Update holidays

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Update
        run: go run github.com/ikawaha/holiday/cmd/update@latest

      - name: Create pull request
        run: |
          git config --local user.email "ikawaha@users.noreply.github.com"
          git config --local user.name "ikawaha"
          DATE=`date +"%Y%m%d"`
          git switch -c "update_$DATE"
          git add holidays.json
          git diff --cached --quiet || git commit -m "Update holidays" || hub pull-request -p -b main -m "Update holidays"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
