name: Update holidays

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Update
        run: go run github.com/ikawaha/holiday/cmd/update@latest

      - name: Git add
        run: |
          git config --local user.email "ikawaha@users.noreply.github.com"
          git config --local user.name "ikawaha"
          DATE=`date +"%Y%m%d"`
          BRANCH="update_$DATE"
          git add holidays.json

      - name: Create PR if there are any updates
        id: create_pr
        if: `git diff --cached --quiet`
        run: |
          git switch -c $BRANCH &&\
          git commit -m "Update holidays" &&\
          git push origin $BRANCH &&\
          hub pull-request -b main -m "Update holidays"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log
        if: steps.create_pr.conclusion == 'skipped'
        run: |
          git commit --allow-empty -m "log: check for updates, no differences"
